class BundledCMapReader {async fetch({name}) {const encoded=window.PDF_CMAPS[name];if(!encoded)throw new Error('CMap unavailable: '+name);return {cMapData:Uint8Array.from(atob(encoded),c=>c.charCodeAt(0)),compressionType:1}}}
const $=id=>document.getElementById(id);pdfjsLib.GlobalWorkerOptions.workerSrc='vendor/pdf.worker.min.js';let doc,bytes,page=1,tool='select',items={},history=[],selected=-1,start,working,imgSource,rendering=false,dirty=false,dragHandle=null;const base=$('base'),canvas=$('overlay'),ctx=canvas.getContext('2d');let scale=1;const say=t=>$('status').textContent=t;
function snapshot(){history.push(JSON.stringify(items));if(history.length>60)history.shift();dirty=true}function list(){return items[page]||(items[page]=[])}function setTool(t){if(t!=='select'){selected=-1;$('editor').hidden=true;draw()}tool=t;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));canvas.style.cursor=t==='select'?'default':'crosshair';say(t==='text'?'入力欄に文字を入れて、PDF上の配置場所を押してください。':t==='select'?'書き込みを選択し、角のつまみでサイズ変更。矢印は両端をドラッグできます。':'PDF上でドラッグしてください。')}
const cache=new Map();function imageFor(src){if(!cache.has(src)){let im=new Image();im.onload=draw;im.src=src;cache.set(src,im)}return cache.get(src)}
function paint(c,o){c.save();c.strokeStyle=o.color;c.fillStyle=o.color;c.lineWidth=o.lineWidth||(o.type==='pen'?3:2);c.lineCap='round';const x=o.x,y=o.y,w=o.w||0,h=o.h||0;if(o.type==='text'){c.font=`${o.size}px sans-serif`;c.textBaseline='top';o.text.split('\n').forEach((t,i)=>c.fillText(t,x,y+i*o.size*1.3))}else if(o.type==='image'){let im=imageFor(o.src);if(im.complete)c.drawImage(im,x,y,w,h)}else if(o.type==='highlight'){c.globalAlpha=.3;c.fillRect(x,y,w,h)}else if(o.type==='rect')c.strokeRect(x,y,w,h);else if(o.type==='ellipse'){c.beginPath();c.ellipse(x+w/2,y+h/2,Math.abs(w/2),Math.abs(h/2),0,0,Math.PI*2);c.stroke()}else if(o.type==='pen'){c.beginPath();o.points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.stroke()}else if(o.type==='arrow'){c.beginPath();c.moveTo(x,y);c.lineTo(x+w,y+h);const a=Math.atan2(h,w);c.moveTo(x+w-14*Math.cos(a-.45),y+h-14*Math.sin(a-.45));c.lineTo(x+w,y+h);c.lineTo(x+w-14*Math.cos(a+.45),y+h-14*Math.sin(a+.45));c.stroke()}c.restore()}
function bounds(o){if(o.type==='pen'){const xs=o.points.map(p=>p.x),ys=o.points.map(p=>p.y);return{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}}if(o.type==='text'){ctx.font=`${o.size}px sans-serif`;return{x:o.x,y:o.y,w:Math.max(...o.text.split('\n').map(t=>ctx.measureText(t).width)),h:o.text.split('\n').length*o.size*1.3}}return{x:Math.min(o.x,o.x+o.w),y:Math.min(o.y,o.y+o.h),w:Math.abs(o.w),h:Math.abs(o.h)}}
function draw(){if(selected<0)$('editor').hidden=true;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();ctx.scale(scale,scale);list().forEach((o,i)=>{paint(ctx,o);if(i===selected){const b=bounds(o);ctx.save();ctx.strokeStyle='#24694f';ctx.lineWidth=1;ctx.setLineDash([5,4]);ctx.strokeRect(b.x,b.y,b.w,b.h);ctx.setLineDash([]);for(const h of handles(o)){ctx.fillStyle='white';ctx.strokeStyle='#24694f';const r=5/scale;ctx.fillRect(h.x-r,h.y-r,r*2,r*2);ctx.strokeRect(h.x-r,h.y-r,r*2,r*2)}ctx.restore()}});if(working&&tool!=='select')paint(ctx,working);ctx.restore()}
async function render(){if(!doc||rendering)return;rendering=true;try{const p=await doc.getPage(page);scale=Number($('zoom').value);const v=p.getViewport({scale});base.width=canvas.width=Math.ceil(v.width);base.height=canvas.height=Math.ceil(v.height);await p.render({canvasContext:base.getContext('2d'),viewport:v}).promise;$('paper').style.display='block';$('empty').style.display='none';$('page').textContent=`${page} / ${doc.numPages}`;$('prev').disabled=page===1;$('next').disabled=page===doc.numPages;draw()}catch(e){throw e}finally{rendering=false}}
async function load(data,name){say('PDFを読み込んでいます…');try{const original=new Uint8Array(data).slice();const next=await pdfjsLib.getDocument({data:original.slice(),isEvalSupported:false,CMapReaderFactory:BundledCMapReader,cMapPacked:true,standardFontDataUrl:'vendor/standard_fonts/'}).promise;doc=next;bytes=original;page=1;items={};history=[];selected=-1;dirty=false;$('filename').textContent=name;$('save').disabled=false;await render();say('準備ができました。左のツールを選んで書き込めます。')}catch(e){say('PDFを開けませんでした。暗号化されたPDFや破損ファイルは読み込めない場合があります。 '+e.message)}}
$('file').onchange=async e=>{const f=e.target.files[0];if(f){if(dirty&&!confirm('未保存の書き込みがあります。別のPDFを開きますか？'))return;await load(await f.arrayBuffer(),f.name)}e.target.value=''};
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{if(b.dataset.tool==='image')$('imageFile').click();else setTool(b.dataset.tool)});
$('imageFile').onchange=e=>{const f=e.target.files[0];if(f){const r=new FileReader();r.onload=()=>{imgSource=r.result;const im=imageFor(imgSource);im.onload=()=>{draw();setTool('image');say('PDF上でドラッグして画像の大きさを指定してください。')}};r.readAsDataURL(f)}e.target.value=''};
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width/scale,y:(e.clientY-r.top)*canvas.height/r.height/scale}}
canvas.onpointerdown=e=>{if(!doc||rendering)return;start=point(e);canvas.setPointerCapture(e.pointerId);if(tool==='select'){dragHandle=selected>=0?hitHandle(list()[selected],start):null;if(dragHandle){snapshot();working=JSON.parse(JSON.stringify(list()[selected]));draw();return}selected=-1;for(let i=list().length-1;i>=0;i--){const b=bounds(list()[i]);if(start.x>=b.x-8&&start.x<=b.x+b.w+8&&start.y>=b.y-8&&start.y<=b.y+b.h+8){selected=i;break}}if(selected>=0){snapshot();working=JSON.parse(JSON.stringify(list()[selected]))}syncEditor();draw();return}if(tool==='text'){const t=$('text').value;if(!t.trim()){say('文字入力欄に、追加する文字を入力してください。');return}snapshot();list().push({type:tool,x:start.x,y:start.y,text:t,size:Number($('size').value),color:$('color').value});selected=-1;draw();return}if(tool==='image'&&!imgSource)return;working={type:tool,x:start.x,y:start.y,w:0,h:0,color:$('color').value,src:tool==='image'?imgSource:undefined,points:tool==='pen'?[start]:undefined};selected=-1};
canvas.onpointermove=e=>{if(!working||!start){if(tool==='select'&&selected>=0){const h=hitHandle(list()[selected],point(e));canvas.style.cursor=h?(h.key==='nw'||h.key==='se'?'nwse-resize':h.key==='ne'||h.key==='sw'?'nesw-resize':'crosshair'):'move'}return;}const p=point(e),dx=p.x-start.x,dy=p.y-start.y;if(tool==='select'){const o=list()[selected];if(dragHandle){resizeAnnotation(o,working,dragHandle,p);draw();return}o.x=working.x+dx;o.y=working.y+dy;if(o.type==='pen')o.points=working.points.map(v=>({x:v.x+dx,y:v.y+dy}))}else if(tool==='pen')working.points.push(p);else{working.w=dx;working.h=dy}draw()};
function finish(){if(working&&tool!=='select'){if(tool==='pen'||Math.abs(working.w)>3&&Math.abs(working.h)>3||tool==='arrow'&&Math.hypot(working.w,working.h)>3){if(tool==='image'){const b=bounds(working);Object.assign(working,b)}snapshot();list().push(working)}}working=null;start=null;dragHandle=null;if(tool==='select')syncEditor();draw()}canvas.onpointerup=finish;canvas.onpointercancel=finish;
$('undo').onclick=()=>{if(history.length){items=JSON.parse(history.pop());selected=-1;draw()}};$('delete').onclick=()=>{if(selected>=0){snapshot();list().splice(selected,1);selected=-1;draw()}else say('「選択・移動」で書き込みを選んでから削除してください。')};
$('prev').onclick=()=>{if(page>1&&!rendering){page--;selected=-1;render().catch(e=>say('ページの表示に失敗しました：'+e.message))}};$('next').onclick=()=>{if(doc&&page<doc.numPages&&!rendering){page++;selected=-1;render().catch(e=>say('ページの表示に失敗しました：'+e.message))}};$('zoom').onchange=()=>render().catch(e=>say('ページの表示に失敗しました：'+e.message));
function download(data,name){const u=URL.createObjectURL(new Blob([data],{type:'application/pdf'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000)}
$('save').onclick=async()=>{if(!bytes)return;$('save').disabled=true;say('PDFを保存しています…');try{const pdf=await PDFLib.PDFDocument.load(bytes);for(const [n,annotations]of Object.entries(items)){if(!annotations.length)continue;const p=pdf.getPages()[Number(n)-1];const view=(await doc.getPage(Number(n))).getViewport({scale:1});const c=document.createElement('canvas');c.width=Math.ceil(view.width*2);c.height=Math.ceil(view.height*2);const g=c.getContext('2d');g.scale(2,2);for(const o of annotations){if(o.type==='image'){const im=imageFor(o.src);if(!im.complete)await new Promise((r,j)=>{im.onload=r;im.onerror=j})}paint(g,o)}const png=await pdf.embedPng(c.toDataURL('image/png'));const angle=((p.getRotation().angle%360)+360)%360,W=p.getWidth(),H=p.getHeight();const position=angle===90?{x:W,y:0,width:H,height:W}:angle===180?{x:W,y:H,width:W,height:H}:angle===270?{x:0,y:H,width:H,height:W}:{x:0,y:0,width:W,height:H};p.drawImage(png,{...position,rotate:PDFLib.degrees(angle)});}

download(await pdf.save(),$('filename').textContent.replace(/\.pdf$/i,'')+'_編集済み.pdf');dirty=false;say('保存しました。ダウンロードしたPDFをご確認ください。')}catch(e){say('保存できませんでした：'+e.message)}finally{$('save').disabled=false}};
$('sample').onclick=async()=>{const p=await PDFLib.PDFDocument.create();for(let i=0;i<2;i++){const s=p.addPage([595,842]);s.drawText('PDF WORKSPACE / SAMPLE '+(i+1),{x:45,y:780,size:20,color:PDFLib.rgb(.15,.4,.3)});s.drawText('Try text, highlight, shapes and images.',{x:45,y:740,size:12});for(let y=660;y>150;y-=65)s.drawRectangle({x:45,y,width:505,height:45,borderColor:PDFLib.rgb(.8,.85,.82),borderWidth:1});s.drawText('Your original PDF stays unchanged.',{x:45,y:80,size:12})}await load(await p.save(),'サンプル.pdf')};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});

function syncEditor(){const o=list()[selected];$('editor').hidden=!o;if(!o)return;const b=bounds(o);$('editTextRow').hidden=o.type!=='text';$('editFontRow').hidden=o.type!=='text';$('editLineRow').hidden=!['pen','rect','ellipse','arrow'].includes(o.type);$('editWRow').hidden=$('editHRow').hidden=o.type==='text';$('editColor').disabled=o.type==='image';$('editColor').value=o.color||'#24694f';$('editText').value=o.text||'';$('editFont').value=o.size||24;$('editLine').value=o.lineWidth||(o.type==='pen'?3:2);$('editX').value=Math.round(o.type==='pen'?b.x:o.x);$('editY').value=Math.round(o.type==='pen'?b.y:o.y);$('editW').value=Math.round(o.type==='arrow'?o.w:Math.max(1,b.w));$('editH').value=Math.round(o.type==='arrow'?o.h:Math.max(1,b.h));$('editW').min=$('editH').min=o.type==='arrow'?'':1;say('選択しました。編集欄の内容を変更して「変更を反映」を押してください。')}
$('applyEdit').onclick=()=>{const o=list()[selected];if(!o)return;const x=Number($('editX').value),y=Number($('editY').value),w=Number($('editW').value),h=Number($('editH').value),size=Number($('editFont').value),line=Number($('editLine').value);if(![x,y,w,h,size,line].every(Number.isFinite)){say('位置とサイズに数値を入力してください。');return}if(o.type==='text'&&(!$('editText').value.trim()||size<6||size>200)){say('文字を入力し、サイズを6〜200に指定してください。');return}if(['pen','rect','ellipse','arrow'].includes(o.type)&&(line<1||line>30)){say('線の太さは1〜30に指定してください。');return}if(o.type!=='text'&&o.type!=='arrow'&&(w<1||h<1)){say('幅と高さは1以上に指定してください。');return}snapshot();const b=bounds(o);if(o.type==='pen'){o.points=o.points.map(p=>({x:x+(p.x-b.x)*(b.w?w/b.w:1),y:y+(p.y-b.y)*(b.h?h/b.h:1)}));o.x=x;o.y=y}else{o.x=x;o.y=y;if(o.type==='text'){o.text=$('editText').value;o.size=size}else if(o.type==='arrow'){o.w=w;o.h=h}else{o.w=w*(o.w<0?-1:1);o.h=h*(o.h<0?-1:1)}}if(o.type!=='image')o.color=$('editColor').value;o.lineWidth=line;draw();syncEditor();say('変更を反映しました。「元に戻す」で取り消せます。')};

function handles(o){if(o.type==='arrow')return[{key:'start',x:o.x,y:o.y},{key:'end',x:o.x+o.w,y:o.y+o.h}];const b=bounds(o);return[{key:'nw',x:b.x,y:b.y},{key:'ne',x:b.x+b.w,y:b.y},{key:'sw',x:b.x,y:b.y+b.h},{key:'se',x:b.x+b.w,y:b.y+b.h}]}
function hitHandle(o,p){return handles(o).find(h=>Math.hypot(h.x-p.x,h.y-p.y)<=12/scale)}
function resizeAnnotation(o,original,handle,p){if(original.type==='arrow'){if(handle.key==='start'){o.x=p.x;o.y=p.y;o.w=original.x+original.w-p.x;o.h=original.y+original.h-p.y}else{o.w=p.x-original.x;o.h=p.y-original.y}return}const b=bounds(original),left=handle.key.includes('w'),top=handle.key.includes('n'),ax=left?b.x+b.w:b.x,ay=top?b.y+b.h:b.y;let w=Math.max(2,Math.abs(p.x-ax)),h=Math.max(2,Math.abs(p.y-ay));let x=Math.min(p.x,ax),y=Math.min(p.y,ay);if(original.type==='text'){const ratio=Math.max(.1,Math.hypot(w,h)/Math.max(1,Math.hypot(b.w,b.h)));o.size=Math.max(6,Math.min(200,original.size*ratio));const actual=o.size/original.size;o.x=left?ax-b.w*actual:ax;o.y=top?ay-b.h*actual:ay;return}if(original.type==='pen'){o.points=original.points.map(v=>({x:x+(v.x-b.x)*(b.w?w/b.w:1),y:y+(v.y-b.y)*(b.h?h/b.h:1)}));o.x=x;o.y=y;return}o.x=x;o.y=y;o.w=w;o.h=h;}
canvas.ondblclick=e=>{if(tool!=='select'||selected<0)return;const o=list()[selected];if(o.type==='text'){syncEditor();$('editText').focus();$('editText').select();say('文字内容を変更して「変更を反映」を押してください。')}};
